/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game.impl;

import master.mdsd.game.AttributeInitializer;
import master.mdsd.game.GamePackage;
import master.mdsd.game.TargetRef;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attribute Initializer</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link master.mdsd.game.impl.AttributeInitializerImpl#getAttributeId <em>Attribute Id</em>}</li>
 *   <li>{@link master.mdsd.game.impl.AttributeInitializerImpl#getAmountValueId <em>Amount Value Id</em>}</li>
 *   <li>{@link master.mdsd.game.impl.AttributeInitializerImpl#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AttributeInitializerImpl extends MinimalEObjectImpl.Container implements AttributeInitializer
{
  /**
   * The default value of the '{@link #getAttributeId() <em>Attribute Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttributeId()
   * @generated
   * @ordered
   */
  protected static final String ATTRIBUTE_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAttributeId() <em>Attribute Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttributeId()
   * @generated
   * @ordered
   */
  protected String attributeId = ATTRIBUTE_ID_EDEFAULT;

  /**
   * The default value of the '{@link #getAmountValueId() <em>Amount Value Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAmountValueId()
   * @generated
   * @ordered
   */
  protected static final int AMOUNT_VALUE_ID_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getAmountValueId() <em>Amount Value Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAmountValueId()
   * @generated
   * @ordered
   */
  protected int amountValueId = AMOUNT_VALUE_ID_EDEFAULT;

  /**
   * The cached value of the '{@link #getTarget() <em>Target</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTarget()
   * @generated
   * @ordered
   */
  protected TargetRef target;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttributeInitializerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.ATTRIBUTE_INITIALIZER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAttributeId()
  {
    return attributeId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAttributeId(String newAttributeId)
  {
    String oldAttributeId = attributeId;
    attributeId = newAttributeId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.ATTRIBUTE_INITIALIZER__ATTRIBUTE_ID, oldAttributeId, attributeId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getAmountValueId()
  {
    return amountValueId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAmountValueId(int newAmountValueId)
  {
    int oldAmountValueId = amountValueId;
    amountValueId = newAmountValueId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.ATTRIBUTE_INITIALIZER__AMOUNT_VALUE_ID, oldAmountValueId, amountValueId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TargetRef getTarget()
  {
    return target;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTarget(TargetRef newTarget, NotificationChain msgs)
  {
    TargetRef oldTarget = target;
    target = newTarget;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GamePackage.ATTRIBUTE_INITIALIZER__TARGET, oldTarget, newTarget);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTarget(TargetRef newTarget)
  {
    if (newTarget != target)
    {
      NotificationChain msgs = null;
      if (target != null)
        msgs = ((InternalEObject)target).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GamePackage.ATTRIBUTE_INITIALIZER__TARGET, null, msgs);
      if (newTarget != null)
        msgs = ((InternalEObject)newTarget).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GamePackage.ATTRIBUTE_INITIALIZER__TARGET, null, msgs);
      msgs = basicSetTarget(newTarget, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.ATTRIBUTE_INITIALIZER__TARGET, newTarget, newTarget));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GamePackage.ATTRIBUTE_INITIALIZER__TARGET:
        return basicSetTarget(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.ATTRIBUTE_INITIALIZER__ATTRIBUTE_ID:
        return getAttributeId();
      case GamePackage.ATTRIBUTE_INITIALIZER__AMOUNT_VALUE_ID:
        return getAmountValueId();
      case GamePackage.ATTRIBUTE_INITIALIZER__TARGET:
        return getTarget();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.ATTRIBUTE_INITIALIZER__ATTRIBUTE_ID:
        setAttributeId((String)newValue);
        return;
      case GamePackage.ATTRIBUTE_INITIALIZER__AMOUNT_VALUE_ID:
        setAmountValueId((Integer)newValue);
        return;
      case GamePackage.ATTRIBUTE_INITIALIZER__TARGET:
        setTarget((TargetRef)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.ATTRIBUTE_INITIALIZER__ATTRIBUTE_ID:
        setAttributeId(ATTRIBUTE_ID_EDEFAULT);
        return;
      case GamePackage.ATTRIBUTE_INITIALIZER__AMOUNT_VALUE_ID:
        setAmountValueId(AMOUNT_VALUE_ID_EDEFAULT);
        return;
      case GamePackage.ATTRIBUTE_INITIALIZER__TARGET:
        setTarget((TargetRef)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.ATTRIBUTE_INITIALIZER__ATTRIBUTE_ID:
        return ATTRIBUTE_ID_EDEFAULT == null ? attributeId != null : !ATTRIBUTE_ID_EDEFAULT.equals(attributeId);
      case GamePackage.ATTRIBUTE_INITIALIZER__AMOUNT_VALUE_ID:
        return amountValueId != AMOUNT_VALUE_ID_EDEFAULT;
      case GamePackage.ATTRIBUTE_INITIALIZER__TARGET:
        return target != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (attributeId: ");
    result.append(attributeId);
    result.append(", amountValueId: ");
    result.append(amountValueId);
    result.append(')');
    return result.toString();
  }

} //AttributeInitializerImpl
