/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game.impl;

import master.mdsd.game.AttributeTypeAttack;
import master.mdsd.game.GamePackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attribute Type Attack</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AttributeTypeAttackImpl extends MinimalEObjectImpl.Container implements AttributeTypeAttack
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttributeTypeAttackImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.ATTRIBUTE_TYPE_ATTACK;
  }

} //AttributeTypeAttackImpl
