/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game.impl;

import java.util.Collection;

import master.mdsd.game.Attribute;
import master.mdsd.game.GamePackage;
import master.mdsd.game.Location;
import master.mdsd.game.LogicOperator;
import master.mdsd.game.Type;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Location</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link master.mdsd.game.impl.LocationImpl#getLocationId <em>Location Id</em>}</li>
 *   <li>{@link master.mdsd.game.impl.LocationImpl#getTypea <em>Typea</em>}</li>
 *   <li>{@link master.mdsd.game.impl.LocationImpl#getTypeb <em>Typeb</em>}</li>
 *   <li>{@link master.mdsd.game.impl.LocationImpl#getCharAtt <em>Char Att</em>}</li>
 *   <li>{@link master.mdsd.game.impl.LocationImpl#getLogicOp <em>Logic Op</em>}</li>
 *   <li>{@link master.mdsd.game.impl.LocationImpl#getTypec <em>Typec</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LocationImpl extends MinimalEObjectImpl.Container implements Location
{
  /**
   * The default value of the '{@link #getLocationId() <em>Location Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocationId()
   * @generated
   * @ordered
   */
  protected static final String LOCATION_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLocationId() <em>Location Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocationId()
   * @generated
   * @ordered
   */
  protected String locationId = LOCATION_ID_EDEFAULT;

  /**
   * The cached value of the '{@link #getTypea() <em>Typea</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypea()
   * @generated
   * @ordered
   */
  protected Type typea;

  /**
   * The cached value of the '{@link #getTypeb() <em>Typeb</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeb()
   * @generated
   * @ordered
   */
  protected Type typeb;

  /**
   * The cached value of the '{@link #getCharAtt() <em>Char Att</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCharAtt()
   * @generated
   * @ordered
   */
  protected EList<Attribute> charAtt;

  /**
   * The cached value of the '{@link #getLogicOp() <em>Logic Op</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLogicOp()
   * @generated
   * @ordered
   */
  protected EList<LogicOperator> logicOp;

  /**
   * The cached value of the '{@link #getTypec() <em>Typec</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypec()
   * @generated
   * @ordered
   */
  protected EList<Type> typec;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LocationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.LOCATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLocationId()
  {
    return locationId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLocationId(String newLocationId)
  {
    String oldLocationId = locationId;
    locationId = newLocationId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.LOCATION__LOCATION_ID, oldLocationId, locationId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Type getTypea()
  {
    return typea;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTypea(Type newTypea, NotificationChain msgs)
  {
    Type oldTypea = typea;
    typea = newTypea;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GamePackage.LOCATION__TYPEA, oldTypea, newTypea);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTypea(Type newTypea)
  {
    if (newTypea != typea)
    {
      NotificationChain msgs = null;
      if (typea != null)
        msgs = ((InternalEObject)typea).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GamePackage.LOCATION__TYPEA, null, msgs);
      if (newTypea != null)
        msgs = ((InternalEObject)newTypea).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GamePackage.LOCATION__TYPEA, null, msgs);
      msgs = basicSetTypea(newTypea, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.LOCATION__TYPEA, newTypea, newTypea));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Type getTypeb()
  {
    return typeb;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTypeb(Type newTypeb, NotificationChain msgs)
  {
    Type oldTypeb = typeb;
    typeb = newTypeb;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GamePackage.LOCATION__TYPEB, oldTypeb, newTypeb);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTypeb(Type newTypeb)
  {
    if (newTypeb != typeb)
    {
      NotificationChain msgs = null;
      if (typeb != null)
        msgs = ((InternalEObject)typeb).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GamePackage.LOCATION__TYPEB, null, msgs);
      if (newTypeb != null)
        msgs = ((InternalEObject)newTypeb).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GamePackage.LOCATION__TYPEB, null, msgs);
      msgs = basicSetTypeb(newTypeb, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.LOCATION__TYPEB, newTypeb, newTypeb));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Attribute> getCharAtt()
  {
    if (charAtt == null)
    {
      charAtt = new EObjectContainmentEList<Attribute>(Attribute.class, this, GamePackage.LOCATION__CHAR_ATT);
    }
    return charAtt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<LogicOperator> getLogicOp()
  {
    if (logicOp == null)
    {
      logicOp = new EObjectContainmentEList<LogicOperator>(LogicOperator.class, this, GamePackage.LOCATION__LOGIC_OP);
    }
    return logicOp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Type> getTypec()
  {
    if (typec == null)
    {
      typec = new EObjectContainmentEList<Type>(Type.class, this, GamePackage.LOCATION__TYPEC);
    }
    return typec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GamePackage.LOCATION__TYPEA:
        return basicSetTypea(null, msgs);
      case GamePackage.LOCATION__TYPEB:
        return basicSetTypeb(null, msgs);
      case GamePackage.LOCATION__CHAR_ATT:
        return ((InternalEList<?>)getCharAtt()).basicRemove(otherEnd, msgs);
      case GamePackage.LOCATION__LOGIC_OP:
        return ((InternalEList<?>)getLogicOp()).basicRemove(otherEnd, msgs);
      case GamePackage.LOCATION__TYPEC:
        return ((InternalEList<?>)getTypec()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.LOCATION__LOCATION_ID:
        return getLocationId();
      case GamePackage.LOCATION__TYPEA:
        return getTypea();
      case GamePackage.LOCATION__TYPEB:
        return getTypeb();
      case GamePackage.LOCATION__CHAR_ATT:
        return getCharAtt();
      case GamePackage.LOCATION__LOGIC_OP:
        return getLogicOp();
      case GamePackage.LOCATION__TYPEC:
        return getTypec();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.LOCATION__LOCATION_ID:
        setLocationId((String)newValue);
        return;
      case GamePackage.LOCATION__TYPEA:
        setTypea((Type)newValue);
        return;
      case GamePackage.LOCATION__TYPEB:
        setTypeb((Type)newValue);
        return;
      case GamePackage.LOCATION__CHAR_ATT:
        getCharAtt().clear();
        getCharAtt().addAll((Collection<? extends Attribute>)newValue);
        return;
      case GamePackage.LOCATION__LOGIC_OP:
        getLogicOp().clear();
        getLogicOp().addAll((Collection<? extends LogicOperator>)newValue);
        return;
      case GamePackage.LOCATION__TYPEC:
        getTypec().clear();
        getTypec().addAll((Collection<? extends Type>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.LOCATION__LOCATION_ID:
        setLocationId(LOCATION_ID_EDEFAULT);
        return;
      case GamePackage.LOCATION__TYPEA:
        setTypea((Type)null);
        return;
      case GamePackage.LOCATION__TYPEB:
        setTypeb((Type)null);
        return;
      case GamePackage.LOCATION__CHAR_ATT:
        getCharAtt().clear();
        return;
      case GamePackage.LOCATION__LOGIC_OP:
        getLogicOp().clear();
        return;
      case GamePackage.LOCATION__TYPEC:
        getTypec().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.LOCATION__LOCATION_ID:
        return LOCATION_ID_EDEFAULT == null ? locationId != null : !LOCATION_ID_EDEFAULT.equals(locationId);
      case GamePackage.LOCATION__TYPEA:
        return typea != null;
      case GamePackage.LOCATION__TYPEB:
        return typeb != null;
      case GamePackage.LOCATION__CHAR_ATT:
        return charAtt != null && !charAtt.isEmpty();
      case GamePackage.LOCATION__LOGIC_OP:
        return logicOp != null && !logicOp.isEmpty();
      case GamePackage.LOCATION__TYPEC:
        return typec != null && !typec.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (locationId: ");
    result.append(locationId);
    result.append(')');
    return result.toString();
  }

} //LocationImpl
