/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link master.mdsd.game.Action#getCharAtt <em>Char Att</em>}</li>
 *   <li>{@link master.mdsd.game.Action#getCharDec <em>Char Dec</em>}</li>
 *   <li>{@link master.mdsd.game.Action#getOp <em>Op</em>}</li>
 *   <li>{@link master.mdsd.game.Action#getEx <em>Ex</em>}</li>
 * </ul>
 *
 * @see master.mdsd.game.GamePackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
  /**
   * Returns the value of the '<em><b>Char Att</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Char Att</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Char Att</em>' containment reference.
   * @see #setCharAtt(CharacterAttr)
   * @see master.mdsd.game.GamePackage#getAction_CharAtt()
   * @model containment="true"
   * @generated
   */
  CharacterAttr getCharAtt();

  /**
   * Sets the value of the '{@link master.mdsd.game.Action#getCharAtt <em>Char Att</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Char Att</em>' containment reference.
   * @see #getCharAtt()
   * @generated
   */
  void setCharAtt(CharacterAttr value);

  /**
   * Returns the value of the '<em><b>Char Dec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Char Dec</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Char Dec</em>' containment reference.
   * @see #setCharDec(CharDec)
   * @see master.mdsd.game.GamePackage#getAction_CharDec()
   * @model containment="true"
   * @generated
   */
  CharDec getCharDec();

  /**
   * Sets the value of the '{@link master.mdsd.game.Action#getCharDec <em>Char Dec</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Char Dec</em>' containment reference.
   * @see #getCharDec()
   * @generated
   */
  void setCharDec(CharDec value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' containment reference.
   * @see #setOp(LogicOperator)
   * @see master.mdsd.game.GamePackage#getAction_Op()
   * @model containment="true"
   * @generated
   */
  LogicOperator getOp();

  /**
   * Sets the value of the '{@link master.mdsd.game.Action#getOp <em>Op</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' containment reference.
   * @see #getOp()
   * @generated
   */
  void setOp(LogicOperator value);

  /**
   * Returns the value of the '<em><b>Ex</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ex</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ex</em>' containment reference.
   * @see #setEx(Expression)
   * @see master.mdsd.game.GamePackage#getAction_Ex()
   * @model containment="true"
   * @generated
   */
  Expression getEx();

  /**
   * Sets the value of the '{@link master.mdsd.game.Action#getEx <em>Ex</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ex</em>' containment reference.
   * @see #getEx()
   * @generated
   */
  void setEx(Expression value);

} // Action
