/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ammo</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see master.mdsd.game.GamePackage#getAmmo()
 * @model
 * @generated
 */
public interface Ammo extends AttributeTypeAttack
{
} // Ammo
