/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attack</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link master.mdsd.game.Attack#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link master.mdsd.game.Attack#getAttributesAttack <em>Attributes Attack</em>}</li>
 *   <li>{@link master.mdsd.game.Attack#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see master.mdsd.game.GamePackage#getAttack()
 * @model
 * @generated
 */
public interface Attack extends Behaviour
{
  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link master.mdsd.game.Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attributes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see master.mdsd.game.GamePackage#getAttack_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

  /**
   * Returns the value of the '<em><b>Attributes Attack</b></em>' containment reference list.
   * The list contents are of type {@link master.mdsd.game.AttributeAttack}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attributes Attack</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes Attack</em>' containment reference list.
   * @see master.mdsd.game.GamePackage#getAttack_AttributesAttack()
   * @model containment="true"
   * @generated
   */
  EList<AttributeAttack> getAttributesAttack();

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link master.mdsd.game.Condition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rules</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see master.mdsd.game.GamePackage#getAttack_Rules()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getRules();

} // Attack
