/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bullet</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link master.mdsd.game.Bullet#getBulletRef <em>Bullet Ref</em>}</li>
 *   <li>{@link master.mdsd.game.Bullet#getAttributesBullet <em>Attributes Bullet</em>}</li>
 * </ul>
 *
 * @see master.mdsd.game.GamePackage#getBullet()
 * @model
 * @generated
 */
public interface Bullet extends Behaviour, AttributeTypeAttack
{
  /**
   * Returns the value of the '<em><b>Bullet Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bullet Ref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bullet Ref</em>' reference.
   * @see #setBulletRef(Bullet)
   * @see master.mdsd.game.GamePackage#getBullet_BulletRef()
   * @model
   * @generated
   */
  Bullet getBulletRef();

  /**
   * Sets the value of the '{@link master.mdsd.game.Bullet#getBulletRef <em>Bullet Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bullet Ref</em>' reference.
   * @see #getBulletRef()
   * @generated
   */
  void setBulletRef(Bullet value);

  /**
   * Returns the value of the '<em><b>Attributes Bullet</b></em>' containment reference list.
   * The list contents are of type {@link master.mdsd.game.Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attributes Bullet</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes Bullet</em>' containment reference list.
   * @see master.mdsd.game.GamePackage#getBullet_AttributesBullet()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributesBullet();

} // Bullet
