/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Char Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link master.mdsd.game.CharType#getCharTypeid <em>Char Typeid</em>}</li>
 * </ul>
 *
 * @see master.mdsd.game.GamePackage#getCharType()
 * @model
 * @generated
 */
public interface CharType extends EObject
{
  /**
   * Returns the value of the '<em><b>Char Typeid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Char Typeid</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Char Typeid</em>' attribute.
   * @see #setCharTypeid(String)
   * @see master.mdsd.game.GamePackage#getCharType_CharTypeid()
   * @model
   * @generated
   */
  String getCharTypeid();

  /**
   * Sets the value of the '{@link master.mdsd.game.CharType#getCharTypeid <em>Char Typeid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Char Typeid</em>' attribute.
   * @see #getCharTypeid()
   * @generated
   */
  void setCharTypeid(String value);

} // CharType
