/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comp Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see master.mdsd.game.GamePackage#getCompOperator()
 * @model
 * @generated
 */
public interface CompOperator extends EObject
{
} // CompOperator
