/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>D</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see master.mdsd.game.GamePackage#getD()
 * @model
 * @generated
 */
public interface D extends LogicOperator
{
} // D
