/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dynamic Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link master.mdsd.game.DynamicEntity#getEntityid <em>Entityid</em>}</li>
 *   <li>{@link master.mdsd.game.DynamicEntity#getCharacter <em>Character</em>}</li>
 *   <li>{@link master.mdsd.game.DynamicEntity#getObject <em>Object</em>}</li>
 *   <li>{@link master.mdsd.game.DynamicEntity#getBehaviour <em>Behaviour</em>}</li>
 * </ul>
 *
 * @see master.mdsd.game.GamePackage#getDynamicEntity()
 * @model
 * @generated
 */
public interface DynamicEntity extends Entity
{
  /**
   * Returns the value of the '<em><b>Entityid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entityid</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entityid</em>' attribute.
   * @see #setEntityid(String)
   * @see master.mdsd.game.GamePackage#getDynamicEntity_Entityid()
   * @model
   * @generated
   */
  String getEntityid();

  /**
   * Sets the value of the '{@link master.mdsd.game.DynamicEntity#getEntityid <em>Entityid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entityid</em>' attribute.
   * @see #getEntityid()
   * @generated
   */
  void setEntityid(String value);

  /**
   * Returns the value of the '<em><b>Character</b></em>' containment reference list.
   * The list contents are of type {@link master.mdsd.game.Character}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Character</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Character</em>' containment reference list.
   * @see master.mdsd.game.GamePackage#getDynamicEntity_Character()
   * @model containment="true"
   * @generated
   */
  EList<master.mdsd.game.Character> getCharacter();

  /**
   * Returns the value of the '<em><b>Object</b></em>' containment reference list.
   * The list contents are of type {@link master.mdsd.game.Object}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Object</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object</em>' containment reference list.
   * @see master.mdsd.game.GamePackage#getDynamicEntity_Object()
   * @model containment="true"
   * @generated
   */
  EList<master.mdsd.game.Object> getObject();

  /**
   * Returns the value of the '<em><b>Behaviour</b></em>' containment reference list.
   * The list contents are of type {@link master.mdsd.game.Behaviour}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Behaviour</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Behaviour</em>' containment reference list.
   * @see master.mdsd.game.GamePackage#getDynamicEntity_Behaviour()
   * @model containment="true"
   * @generated
   */
  EList<Behaviour> getBehaviour();

} // DynamicEntity
