/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>GTE</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see master.mdsd.game.GamePackage#getGTE()
 * @model
 * @generated
 */
public interface GTE extends CompOperator
{
} // GTE
