/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Location</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link master.mdsd.game.Location#getLocationId <em>Location Id</em>}</li>
 *   <li>{@link master.mdsd.game.Location#getTypea <em>Typea</em>}</li>
 *   <li>{@link master.mdsd.game.Location#getTypeb <em>Typeb</em>}</li>
 * </ul>
 *
 * @see master.mdsd.game.GamePackage#getLocation()
 * @model
 * @generated
 */
public interface Location extends EObject
{
  /**
   * Returns the value of the '<em><b>Location Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Location Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Location Id</em>' attribute.
   * @see #setLocationId(String)
   * @see master.mdsd.game.GamePackage#getLocation_LocationId()
   * @model
   * @generated
   */
  String getLocationId();

  /**
   * Sets the value of the '{@link master.mdsd.game.Location#getLocationId <em>Location Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Location Id</em>' attribute.
   * @see #getLocationId()
   * @generated
   */
  void setLocationId(String value);

  /**
   * Returns the value of the '<em><b>Typea</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Typea</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Typea</em>' containment reference.
   * @see #setTypea(Type)
   * @see master.mdsd.game.GamePackage#getLocation_Typea()
   * @model containment="true"
   * @generated
   */
  Type getTypea();

  /**
   * Sets the value of the '{@link master.mdsd.game.Location#getTypea <em>Typea</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Typea</em>' containment reference.
   * @see #getTypea()
   * @generated
   */
  void setTypea(Type value);

  /**
   * Returns the value of the '<em><b>Typeb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Typeb</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Typeb</em>' containment reference.
   * @see #setTypeb(Type)
   * @see master.mdsd.game.GamePackage#getLocation_Typeb()
   * @model containment="true"
   * @generated
   */
  Type getTypeb();

  /**
   * Sets the value of the '{@link master.mdsd.game.Location#getTypeb <em>Typeb</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Typeb</em>' containment reference.
   * @see #getTypeb()
   * @generated
   */
  void setTypeb(Type value);

} // Location
