/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logic Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see master.mdsd.game.GamePackage#getLogicOperator()
 * @model
 * @generated
 */
public interface LogicOperator extends EObject
{
} // LogicOperator
