/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logic Operator Loop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link master.mdsd.game.LogicOperatorLoop#getLogicOp <em>Logic Op</em>}</li>
 *   <li>{@link master.mdsd.game.LogicOperatorLoop#getIntAtt <em>Int Att</em>}</li>
 *   <li>{@link master.mdsd.game.LogicOperatorLoop#getLop <em>Lop</em>}</li>
 * </ul>
 *
 * @see master.mdsd.game.GamePackage#getLogicOperatorLoop()
 * @model
 * @generated
 */
public interface LogicOperatorLoop extends EObject
{
  /**
   * Returns the value of the '<em><b>Logic Op</b></em>' containment reference list.
   * The list contents are of type {@link master.mdsd.game.LogicOperator}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Logic Op</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logic Op</em>' containment reference list.
   * @see master.mdsd.game.GamePackage#getLogicOperatorLoop_LogicOp()
   * @model containment="true"
   * @generated
   */
  EList<LogicOperator> getLogicOp();

  /**
   * Returns the value of the '<em><b>Int Att</b></em>' containment reference list.
   * The list contents are of type {@link master.mdsd.game.IntAtt}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Int Att</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int Att</em>' containment reference list.
   * @see master.mdsd.game.GamePackage#getLogicOperatorLoop_IntAtt()
   * @model containment="true"
   * @generated
   */
  EList<IntAtt> getIntAtt();

  /**
   * Returns the value of the '<em><b>Lop</b></em>' containment reference list.
   * The list contents are of type {@link master.mdsd.game.LogicOperatorLoop}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lop</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lop</em>' containment reference list.
   * @see master.mdsd.game.GamePackage#getLogicOperatorLoop_Lop()
   * @model containment="true"
   * @generated
   */
  EList<LogicOperatorLoop> getLop();

} // LogicOperatorLoop
