/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link master.mdsd.game.Object#getAtt <em>Att</em>}</li>
 * </ul>
 *
 * @see master.mdsd.game.GamePackage#getObject()
 * @model
 * @generated
 */
public interface Object extends DynamicEntity
{
  /**
   * Returns the value of the '<em><b>Att</b></em>' containment reference list.
   * The list contents are of type {@link master.mdsd.game.Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Att</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Att</em>' containment reference list.
   * @see master.mdsd.game.GamePackage#getObject_Att()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAtt();

} // Object
