/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pathfinding</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link master.mdsd.game.Pathfinding#getAttPathfinding <em>Att Pathfinding</em>}</li>
 *   <li>{@link master.mdsd.game.Pathfinding#getConditions <em>Conditions</em>}</li>
 * </ul>
 *
 * @see master.mdsd.game.GamePackage#getPathfinding()
 * @model
 * @generated
 */
public interface Pathfinding extends Behaviour
{
  /**
   * Returns the value of the '<em><b>Att Pathfinding</b></em>' containment reference list.
   * The list contents are of type {@link master.mdsd.game.Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Att Pathfinding</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Att Pathfinding</em>' containment reference list.
   * @see master.mdsd.game.GamePackage#getPathfinding_AttPathfinding()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttPathfinding();

  /**
   * Returns the value of the '<em><b>Conditions</b></em>' containment reference list.
   * The list contents are of type {@link master.mdsd.game.Condition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conditions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions</em>' containment reference list.
   * @see master.mdsd.game.GamePackage#getPathfinding_Conditions()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditions();

} // Pathfinding
