/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link master.mdsd.game.Rule#getRuleSetup <em>Rule Setup</em>}</li>
 *   <li>{@link master.mdsd.game.Rule#getToDoAction <em>To Do Action</em>}</li>
 * </ul>
 *
 * @see master.mdsd.game.GamePackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>Rule Setup</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rule Setup</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rule Setup</em>' containment reference.
   * @see #setRuleSetup(RuleSetup)
   * @see master.mdsd.game.GamePackage#getRule_RuleSetup()
   * @model containment="true"
   * @generated
   */
  RuleSetup getRuleSetup();

  /**
   * Sets the value of the '{@link master.mdsd.game.Rule#getRuleSetup <em>Rule Setup</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rule Setup</em>' containment reference.
   * @see #getRuleSetup()
   * @generated
   */
  void setRuleSetup(RuleSetup value);

  /**
   * Returns the value of the '<em><b>To Do Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To Do Action</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>To Do Action</em>' containment reference.
   * @see #setToDoAction(Action)
   * @see master.mdsd.game.GamePackage#getRule_ToDoAction()
   * @model containment="true"
   * @generated
   */
  Action getToDoAction();

  /**
   * Sets the value of the '{@link master.mdsd.game.Rule#getToDoAction <em>To Do Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To Do Action</em>' containment reference.
   * @see #getToDoAction()
   * @generated
   */
  void setToDoAction(Action value);

} // Rule
