/**
 * generated by Xtext 2.10.0
 */
package master.mdsd.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link master.mdsd.game.Type#getValueId <em>Value Id</em>}</li>
 *   <li>{@link master.mdsd.game.Type#getValueIdVec <em>Value Id Vec</em>}</li>
 * </ul>
 *
 * @see master.mdsd.game.GamePackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
  /**
   * Returns the value of the '<em><b>Value Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Id</em>' attribute.
   * @see #setValueId(String)
   * @see master.mdsd.game.GamePackage#getType_ValueId()
   * @model
   * @generated
   */
  String getValueId();

  /**
   * Sets the value of the '{@link master.mdsd.game.Type#getValueId <em>Value Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Id</em>' attribute.
   * @see #getValueId()
   * @generated
   */
  void setValueId(String value);

  /**
   * Returns the value of the '<em><b>Value Id Vec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Id Vec</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Id Vec</em>' containment reference.
   * @see #setValueIdVec(VECTOR)
   * @see master.mdsd.game.GamePackage#getType_ValueIdVec()
   * @model containment="true"
   * @generated
   */
  VECTOR getValueIdVec();

  /**
   * Sets the value of the '{@link master.mdsd.game.Type#getValueIdVec <em>Value Id Vec</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Id Vec</em>' containment reference.
   * @see #getValueIdVec()
   * @generated
   */
  void setValueIdVec(VECTOR value);

} // Type
